#############################################################################
#                  IMPINJ CONFIDENTIAL AND PROPRIETARY                      #
#                                                                           #
# This source code is the property of Impinj, Inc. Your use of this source  #
# code in whole or in part is subject to your applicable license terms      #
# from Impinj.                                                              #
# Contact support@impinj.com for a copy of the applicable Impinj license    #
# terms.                                                                    #
#                                                                           #
# (c) Copyright 2020 - 2021 Impinj, Inc. All rights reserved.               #
#                                                                           #
#############################################################################

from ctypes import *
from enum import IntEnum


# IPJ_autogen | generate_c2python_fifo_data {
class EventPacketType(IntEnum):
    TxRampUp = 1
    TxRampDown = 2
    InventoryRoundSummary = 3
    QChanged = 4
    TagRead = 5
    Gen2Transaction = 7
    ContinuousInventorySummary = 8
    HelloWorld = 9
    Custom = 10
    PowerControlLoopSummary = 11
    MeasureRssiSummary = 12
    AggregateOpSummary = 13
    Halted = 14
    InvalidPacket = 240
    WriteProfileData = 253
    SjcMeasurement = 254
    Debug = 255

# Autogenerated python shim components for the fifo packets
class TxRampUp(Structure):
    _pack_ = 1
    _fields_ = [
    ('carrier_frequency', c_uint32),
    ]

class RampDownReason(IntEnum):
    RampDownHost       = 1
    RampDownRegulatory = 2

class TxRampDown(Structure):
    _pack_ = 1
    _fields_ = [
    ('reason', c_uint8),
    ('packet_rfu_1', c_uint8),
    ('packet_rfu_2', c_uint8),
    ('packet_rfu_3', c_uint8),
    ]

class InventorySummaryReason(IntEnum):
    InventorySummaryDone          = 1
    InventorySummaryHost          = 2
    InventorySummaryRegulatory    = 3
    InventorySummaryEventFifoFull = 4
    InventorySummaryTxNotRampedUp = 5
    InventorySummaryInvalidParam  = 6
    InventorySummaryLmacOverload  = 7

class InventoryRoundSummary(Structure):
    _pack_ = 1
    _fields_ = [
    ('duration_us', c_uint32),
    ('total_slots', c_uint32),
    ('num_slots', c_uint16),
    ('empty_slots', c_uint16),
    ('single_slots', c_uint16),
    ('collided_slots', c_uint16),
    ('reason', c_uint8),
    ('final_q', c_uint8),
    ('min_q_count', c_uint8),
    ('queries_since_valid_epc_count', c_uint8),
    ]

class QChanged(Structure):
    _pack_ = 1
    _fields_ = [
    ('num_slots', c_uint16),
    ('empty_slots', c_uint16),
    ('single_slots', c_uint16),
    ('collided_slots', c_uint16),
    ('q_value', c_uint8),
    ('sent_query', c_uint8),
    ('packet_rfu_1', c_uint8),
    ('packet_rfu_2', c_uint8),
    ]

class TagReadType(IntEnum):
    TagReadTypeEpc              = 1
    TagReadTypeEpcWithTid       = 2
    TagReadTypeEpcWithFastIdTid = 3

class TagRead(Structure):
    _pack_ = 1
    _fields_ = [
    ('rssi', c_uint16),
    ('rf_phase_begin', c_uint16),
    ('rf_phase_end', c_uint16),
    ('halted_handle', c_uint16),
    ('type', c_uint8),
    ('tid_offset', c_uint8),
    ('halted_on_tag', c_bool),
    ('packet_rfu', c_uint8),
    ]

class Gen2TransactionStatus(IntEnum):
    Gen2TransactionStatusOk               = 1
    Gen2TransactionStatusBadCrc           = 2
    Gen2TransactionStatusNoReply          = 3
    Gen2TransactionStatusInvalidReplyType = 4
    Gen2TransactionStatusCoverCodeFailed  = 5

class Gen2Transaction(Structure):
    _pack_ = 1
    _fields_ = [
    ('transaction_id', c_uint8),
    ('status', c_uint8),
    ('valid_path_metrics', c_bool),
    ('packet_rfu', c_uint8),
    ('rf_phase_begin', c_uint16),
    ('rf_phase_end', c_uint16),
    ('rssi', c_uint16),
    ('num_bits', c_uint16),
    ]

class ContinuousInventorySummary(Structure):
    _pack_ = 1
    _fields_ = [
    ('duration_us', c_uint32),
    ('number_of_inventory_rounds', c_uint32),
    ('number_of_tags', c_uint32),
    ('reason', c_uint8),
    ('last_op_id', c_uint8),
    ('last_op_error', c_uint8),
    ('packet_rfu_1', c_uint8),
    ]

class HelloWorld(Structure):
    _pack_ = 1
    _fields_ = [
    ('sku', c_uint16),
    ('reset_reason', c_uint8),
    ('crash_info_conditional', c_uint8),
    ]

class Custom(Structure):
    _pack_ = 1
    _fields_ = [
    ('payload_len', c_uint32),
    ]

class PowerControlLoopSummary(Structure):
    _pack_ = 1
    _fields_ = [
    ('iterations_taken', c_uint32),
    ('final_error', c_int16),
    ('final_tx_fine_gain', c_int16),
    ]

class MeasureRssiSummary(Structure):
    _pack_ = 1
    _fields_ = [
    ('rssi_linear', c_uint32),
    ('rssi_log2', c_uint16),
    ('rssi_count', c_uint16),
    ]

class AggregateOpSummary(Structure):
    _pack_ = 1
    _fields_ = [
    ('op_run_count', c_uint16),
    ('write_count', c_uint16),
    ('insert_fifo_count', c_uint16),
    ('final_buffer_byte_index', c_uint16),
    ('total_jump_count', c_uint16),
    ('last_inner_op_run', c_uint8),
    ('last_inner_op_error', c_uint8),
    ]

class Halted(Structure):
    _pack_ = 1
    _fields_ = [
    ('halted_handle', c_uint16),
    ('reason', c_uint8),
    ('packet_rfu', c_uint8),
    ]

class InvalidPacket(Structure):
    _pack_ = 1
    _fields_ = [
    ('packet_rfu', c_uint32),
    ]

class WriteProfileData(Structure):
    _pack_ = 1
    _fields_ = [
    ('file_no', c_int32),
    ('payload_length', c_uint32),
    ]

class SjcMeasurement(Structure):
    _pack_ = 1
    _fields_ = [
    ('cdac_i', c_int8),
    ('cdac_q', c_int8),
    ('rx_atten', c_uint8),
    ('flags', c_uint8),
    ('residue_i', c_int32),
    ('residue_q', c_int32),
    ]

class Debug(Structure):
    _pack_ = 1
    _fields_ = [
    ('payload_len', c_uint32),
    ]


class PacketData(Union):
    _fields_ = [
        ('tx_ramp_up', TxRampUp),
        ('tx_ramp_down', TxRampDown),
        ('inventory_round_summary', InventoryRoundSummary),
        ('q_changed', QChanged),
        ('tag_read', TagRead),
        ('gen2_transaction', Gen2Transaction),
        ('continuous_inventory_summary', ContinuousInventorySummary),
        ('hello_world', HelloWorld),
        ('custom', Custom),
        ('power_control_loop_summary', PowerControlLoopSummary),
        ('measure_rssi_summary', MeasureRssiSummary),
        ('aggregate_op_summary', AggregateOpSummary),
        ('halted', Halted),
        ('invalid_packet', InvalidPacket),
        ('write_profile_data', WriteProfileData),
        ('sjc_measurement', SjcMeasurement),
        ('debug', Debug),
        ('raw', c_uint8 * 1)
    ]

class PacketHeader(Structure):
    _fields_ = [
    ('packet_length', c_uint8),
    ('packet_type', c_uint8),
    ('sha', c_uint16),
    ('us_counter', c_uint32),
    ]
# IPJ_autogen }
